### ISSUE TITLE
Botania r1.8 231+

### ISSUE THREAD

**Issue by Shadows-of-Fire** [SpitefulFox/ForbiddenMagic#93]
As of the aforementioned botania version, Forbidden magic fails to load its ForbiddenBotany submodule, instead throwing 
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: fox.spiteful.forbidden.compat.Compat$ItemNotFoundException: Unable to find item manaPetal in mod Botania! Are you using the correct version of the mod?
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.compat.Compat.getItem(Compat.java:387)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.compat.ForbiddenBotany.flowerPowerHippymancy(ForbiddenBotany.java:42)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.compat.Compat.compatify(Compat.java:161)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.Forbidden.outro(Forbidden.java:80)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:07:24] [Client thread/INFO] [STDERR/ForbiddenMagic]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

This is caused by Vazkii's removal of mana petals since that version.

**Comment by SpitefulFox** [comment]
Try updating.
