### ISSUE TITLE
Server crash with onDeath event

### ISSUE THREAD

**Issue by LemADEC** [SpitefulFox/ForbiddenMagic#98]
As observed with Forbidden Magic-1.7.10-0.572.jar

```
[19:30:03 ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Lnet/minecraft/client/renderer/ThreadDownloadImageData;
>       at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_65]
>       at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_65]
>       at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_65]
>       at fox.spiteful.forbidden.XPReflectionHelper.getField(XPReflectionHelper.java:10) ~[XPReflectionHelper.class:?]
>       at fox.spiteful.forbidden.XPReflectionHelper.getXP(XPReflectionHelper.java:23) ~[XPReflectionHelper.class:?]
>       at fox.spiteful.forbidden.FMEventHandler.onDeath(FMEventHandler.java:264) ~[FMEventHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_608_FMEventHandler_onDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
>       at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:313) ~[ForgeHooks.class:1.7.10-1614.UNOFFICIAL]
>       at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1016) ~[sv.class:?]
>       at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:335) ~[yv.class:?]
>       at mca.entity.EntityHuman.func_70645_a(EntityHuman.java:544) ~[EntityHuman.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:980) ~[sv.class:?]
>       at com.brandon3055.draconicevolution.common.items.tools.baseclasses.ToolHandler.AOEAttack(ToolHandler.java:219) ~[ToolHandler.class:?]
>       at com.brandon3055.draconicevolution.common.items.weapons.DraconicSword.onLeftClickEntity(DraconicSword.java:84) ~[DraconicSword.class:?]
>       at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1362) ~[yz.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java) ~[mw.class:?]
>       at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source) ~[ServerPlayerAPI.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java) ~[mw.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1558) ~[nh.class:?]
>       at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) ~[ja.class:?]
>       at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) ~[ja.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) ~[nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) ~[MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.ThreadDownloadImageData
>       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_65]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_65]
>       ... 30 more
```

**Comment by SpitefulFox** [comment]
Could you give a little more detail about the circumstances of the crash?

**Comment by LemADEC** [comment]
From what I read in the crash log, a player used a draconic evolution (sword?) which killed an MinecraftComesAlive villager though its area effect, which triggered the onDeath event.
I haven't play with ForbiddenMagic long enough to understand why XP are relevants for villagers or the weapon used. Maybe a specific enchant or potion effect?

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/14/16 7:30 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Lnet/minecraft/client/renderer/ThreadDownloadImageData;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at fox.spiteful.forbidden.XPReflectionHelper.getField(XPReflectionHelper.java:10)
	at fox.spiteful.forbidden.XPReflectionHelper.getXP(XPReflectionHelper.java:23)
	at fox.spiteful.forbidden.FMEventHandler.onDeath(FMEventHandler.java:264)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_608_FMEventHandler_onDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:313)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1016)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:335)
	at mca.entity.EntityHuman.func_70645_a(EntityHuman.java:544)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:980)
	at com.brandon3055.draconicevolution.common.items.tools.baseclasses.ToolHandler.AOEAttack(ToolHandler.java:219)
	at com.brandon3055.draconicevolution.common.items.weapons.DraconicSword.onLeftClickEntity(DraconicSword.java:84)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1362)
	at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1558)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.ThreadDownloadImageData
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1614.UNOFFICIAL
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1901765152 bytes (1813 MB) / 4081057792 bytes (3892 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 20 total; -Xms3G -Xmx7G -XX:+UseG1GC -XX:+UseStringDeduplication -XX:ParallelGCThreads=2 -XX:+CMSClassUnloadingEnabled -XX:+CMSIncrementalPacing -XX:+AggressiveOpts -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc -Xss4M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 36586, allocated: 13, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 118 mods loaded, 118 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.UNOFFICIAL.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.UNOFFICIAL.jar) 
	UCHIJAAAA	kimagine{0.1} [KImagine] (minecraft.jar) 
	UCHIJAAAA	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	gasesCore{1.6.2} [Glenn's Gases Core] (minecraft.jar) 
	UCHIJAAAA	gasesFrameworkCore{1.1.2} [Gases Framework Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8d} [Adventure Backpack] (adventurebackpack-1.7.10-0.8d-Unofficial2.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.4.6-pre2} [AgriCraft] (AgriCraft-1.7.10-1.4.6-pre2.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	DCsAppleMilk{1.7.10_2.8o} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.8o.jar) 
	UCHIJAAAA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.8o.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.38.1.98} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	Grinder{4.0.0} [Grinder] (AttachableGrinder-4.0.0.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	Automagy{0.27} [Automagy] (Automagy-1.7.10-0.27.jar) 
	UCHIJAAAA	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1521-universal.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	bookshelf{1.0.4.172} [Bookshelf] (Bookshelf-1.7.10-1.0.4.172.jar) 
	UCHIJAAAA	Botania{r1.8-245} [Botania] (Botania r1.8-245.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.10} [Brandon's Core] (BrandonsCore-1.0.0.10-bugfix.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	clockworkphase{1.7.10_1.0f} [Clockwork Phase] (clockworkphase-1.7.10_1.0f.jar) 
	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAAAA	craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	doggytalents{v1.9.0h} [Doggy Talents] (DoggyTalents-1.7.10-v1.9.0h-universal.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2-snapshot_9} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore-1.13.jar) 
	UCHIJAAAA	Dynmap{2.2-143} [Dynmap] (Dynmap-2.2-forge-1.7.10.jar) 
	UCHIJAAAA	eplus{4.0.0..73} [Enchanting Plus] (EnchantingPlus-1.7.10-4.0.0.74.jar) 
	UCHIJAAAA	essentialcraft{4.6.1710.63} [Essential Craft 3] (EssentialCraftv4.6.1710.63.jar) 
	UCHIJAAAA	essenthaum{1.1.1710.0} [Essential Thaumaturgy] (essentialthaum-1.1.1710.11.jar) 
	UCHIJAAAA	evilcraft{0.9.2} [EvilCraft] (EvilCraft-1.7.10-0.9.2.jar) 
	UCHIJAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.2} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.2-19.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCHIJAAAA	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	UCHIJAAAA	Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.572} [Forbidden Magic] (Forbidden Magic-1.7.10-0.572.jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	gasesFramework{1.1.2} [Gases Framework] (gasesFramework-1.7.10-1.1.2.jar) 
	UCHIJAAAA	gases{1.6.2} [Glenn's Gases] (gases-1.7.10-1.6.2.jar) 
	UCHIJAAAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	InventoryPets{1.3.8} [Inventory Pets] (inventorypets-1.7.10-1.3.8-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	lance{2.6.2.1710} [Lance Mod] (lance-2.6.2.1710.jar) 
	UCHIJAAAA	reaper_lantern{1.47} [Lantern mod] (Lantern1.47[1.7.10].jar) 
	UCHIJAAAA	levelup{0.10} [Level Up!] (LevelUp!-0.10(1.7.10).jar) 
	UCHIJAAAA	llibrary{0.6.2} [LLibrary] (llibrary-0.6.2-1.7.10.jar) 
	UCHIJAAAA	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCHIJAAAA	magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar) 
	UCHIJAAAA	magicalcropsdeco{4.0.0_PUBLIC_BETA_4a} [Magical Crops: Decorative] (magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar) 
	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.1.1.0} [Minecraft Comes Alive] (MCA-1.7.10-5.1.1.0-universal.jar) 
	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UCHIJAAAA	AS_Minions{1.9.4} [Minions] (Minions-1.7.10.jar) 
	UCHIJAAAA	mowziesmobs{1.2.5-undefined} [Mowzie's Mobs] (Mowzie's Mobs-1.2.6.jar) 
	UCHIJAAAA	AS_MultiMine{1.4.4} [Multi Mine] (MultiMine-1.7.10.jar) 
	UCHIJAAAA	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	pchan3{0.7} [PChan3 mods] (PChan3Mods-0.7(1.7.10).jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCHIJAAAA	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
	UCHIJAAAA	DustMod{2.0.0} [Runic Dust Mod] (Runic-Dust-Mod-1.7.10-2.0.6.jar) 
	UCHIJAAAA	DustExample{1.0} [Dust Mod Example 1] (Runic-Dust-Mod-1.7.10-2.0.6.jar) 
	UCHIJAAAA	DustModDefaults{1.6.1} [Dust mod default Rune Pack] (Runic-Dust-Mod-1.7.10-2.0.6.jar) 
	UCHIJAAAA	DustModTestPack{0.03} [Dust mod Test pack] (Runic-Dust-Mod-1.7.10-2.0.6.jar) 
	UCHIJAAAA	Sampler{1.39} [Sampler] (sampler-1.39.jar) 
	UCHIJAAAA	SanguineExtras{1.3.2} [Sanguine Utilities] (Sanguine Utilities-1.3.2.jar) 
	UCHIJAAAA	SSR{rc3} [Soul Shards Reborn] (SSR-rc3.jar) 
	UCHIJAAAA	supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) 
	UCHIJAAAA	TaintedMagic{1.1.6.4} [Tainted Magic] (TaintedMagic-1.1.6.4.jar) 
	UCHIJAAAA	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHIJAAAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJAAAA	elysium{1.0} [The Elysium] (TheElysium-1.7.x-1.0.3.jar) 
	UCHIJAAAA	erebus{0.4.1} [Erebus] (TheErebus-0.4.1.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	vending{1.2.3} [vending] (vending-v1.2.3.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 14 / 50; [xxx]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by LemADEC** [comment]
Could it be that the attacking entity wasn't defined or a fake player?

**Comment by SpitefulFox** [comment]
There's absolutely zero reason this should be happening.  Since you don't have any info on the crash, I'm going to have to close this.  Next patch to FM should add a little more redundant padding to the XP code, so maybe that'll help you.

**Comment by SpitefulFox** [comment]
Hmm, on closer look, there may be some silly oversight in the XP grabbing code that isn't playing nice with somebody else's mod.  Should be fixed in the next patch, at any rate.
